/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const SearchId = IDL.Nat;
export const Timestamp = IDL.Int;
export const RankResult = IDL.Record({
  'lat' : IDL.Float64,
  'lng' : IDL.Float64,
  'rank' : IDL.Opt(IDL.Nat),
});
export const PartialScan = IDL.Record({
  'startedAt' : Timestamp,
  'businessName' : IDL.Text,
  'results' : IDL.Vec(RankResult),
  'address' : IDL.Text,
  'keyword' : IDL.Text,
  'centerLat' : IDL.Float64,
  'centerLng' : IDL.Float64,
});
export const UserId = IDL.Principal;
export const SavedSearch = IDL.Record({
  'id' : SearchId,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'businessName' : IDL.Text,
  'results' : IDL.Vec(RankResult),
  'address' : IDL.Text,
  'keyword' : IDL.Text,
  'centerLat' : IDL.Float64,
  'centerLng' : IDL.Float64,
});
export const SaveSearchInput = IDL.Record({
  'businessName' : IDL.Text,
  'results' : IDL.Vec(RankResult),
  'address' : IDL.Text,
  'keyword' : IDL.Text,
  'centerLat' : IDL.Float64,
  'centerLng' : IDL.Float64,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearLastPartialScan' : IDL.Func([], [], []),
  'deleteSavedSearch' : IDL.Func([SearchId], [], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getGridPoints' : IDL.Func(
      [IDL.Float64, IDL.Float64],
      [IDL.Vec(IDL.Tuple(IDL.Float64, IDL.Float64))],
      ['query'],
    ),
  'getLastPartialScan' : IDL.Func([], [IDL.Opt(PartialScan)], ['query']),
  'getSavedSearch' : IDL.Func([SearchId], [IDL.Opt(SavedSearch)], ['query']),
  'getSerpApiKey' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listSavedSearches' : IDL.Func([], [IDL.Vec(SavedSearch)], ['query']),
  'queryGridPoint' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64, IDL.Float64, IDL.Nat],
      [IDL.Opt(IDL.Nat)],
      [],
    ),
  'saveSearch' : IDL.Func([SaveSearchInput], [SearchId], []),
  'setSerpApiKey' : IDL.Func([IDL.Text], [], []),
  'startScan' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Float64],
      [],
      [],
    ),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const SearchId = IDL.Nat;
  const Timestamp = IDL.Int;
  const RankResult = IDL.Record({
    'lat' : IDL.Float64,
    'lng' : IDL.Float64,
    'rank' : IDL.Opt(IDL.Nat),
  });
  const PartialScan = IDL.Record({
    'startedAt' : Timestamp,
    'businessName' : IDL.Text,
    'results' : IDL.Vec(RankResult),
    'address' : IDL.Text,
    'keyword' : IDL.Text,
    'centerLat' : IDL.Float64,
    'centerLng' : IDL.Float64,
  });
  const UserId = IDL.Principal;
  const SavedSearch = IDL.Record({
    'id' : SearchId,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'businessName' : IDL.Text,
    'results' : IDL.Vec(RankResult),
    'address' : IDL.Text,
    'keyword' : IDL.Text,
    'centerLat' : IDL.Float64,
    'centerLng' : IDL.Float64,
  });
  const SaveSearchInput = IDL.Record({
    'businessName' : IDL.Text,
    'results' : IDL.Vec(RankResult),
    'address' : IDL.Text,
    'keyword' : IDL.Text,
    'centerLat' : IDL.Float64,
    'centerLng' : IDL.Float64,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearLastPartialScan' : IDL.Func([], [], []),
    'deleteSavedSearch' : IDL.Func([SearchId], [], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getGridPoints' : IDL.Func(
        [IDL.Float64, IDL.Float64],
        [IDL.Vec(IDL.Tuple(IDL.Float64, IDL.Float64))],
        ['query'],
      ),
    'getLastPartialScan' : IDL.Func([], [IDL.Opt(PartialScan)], ['query']),
    'getSavedSearch' : IDL.Func([SearchId], [IDL.Opt(SavedSearch)], ['query']),
    'getSerpApiKey' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listSavedSearches' : IDL.Func([], [IDL.Vec(SavedSearch)], ['query']),
    'queryGridPoint' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, IDL.Float64, IDL.Nat],
        [IDL.Opt(IDL.Nat)],
        [],
      ),
    'saveSearch' : IDL.Func([SaveSearchInput], [SearchId], []),
    'setSerpApiKey' : IDL.Func([IDL.Text], [], []),
    'startScan' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Float64],
        [],
        [],
      ),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };