/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface PartialScan {
  'startedAt' : Timestamp,
  'businessName' : string,
  'results' : Array<RankResult>,
  'address' : string,
  'keyword' : string,
  'centerLat' : number,
  'centerLng' : number,
}
export interface RankResult {
  'lat' : number,
  'lng' : number,
  'rank' : [] | [bigint],
}
export interface SaveSearchInput {
  'businessName' : string,
  'results' : Array<RankResult>,
  'address' : string,
  'keyword' : string,
  'centerLat' : number,
  'centerLng' : number,
}
export interface SavedSearch {
  'id' : SearchId,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'businessName' : string,
  'results' : Array<RankResult>,
  'address' : string,
  'keyword' : string,
  'centerLat' : number,
  'centerLng' : number,
}
export type SearchId = bigint;
export type Timestamp = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserId = Principal;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearLastPartialScan' : ActorMethod<[], undefined>,
  'deleteSavedSearch' : ActorMethod<[SearchId], undefined>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getGridPoints' : ActorMethod<[number, number], Array<[number, number]>>,
  'getLastPartialScan' : ActorMethod<[], [] | [PartialScan]>,
  'getSavedSearch' : ActorMethod<[SearchId], [] | [SavedSearch]>,
  'getSerpApiKey' : ActorMethod<[], [] | [string]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listSavedSearches' : ActorMethod<[], Array<SavedSearch>>,
  'queryGridPoint' : ActorMethod<
    [string, string, number, number, bigint],
    [] | [bigint]
  >,
  'saveSearch' : ActorMethod<[SaveSearchInput], SearchId>,
  'setSerpApiKey' : ActorMethod<[string], undefined>,
  'startScan' : ActorMethod<
    [string, string, string, number, number],
    undefined
  >,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];