/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type SearchId = bigint;
export type UserId = Principal;
export type Timestamp = bigint;
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface SavedSearch {
    id: SearchId;
    userId: UserId;
    createdAt: Timestamp;
    businessName: string;
    results: Array<RankResult>;
    address: string;
    keyword: string;
    centerLat: number;
    centerLng: number;
}
export interface SaveSearchInput {
    businessName: string;
    results: Array<RankResult>;
    address: string;
    keyword: string;
    centerLat: number;
    centerLng: number;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface RankResult {
    lat: number;
    lng: number;
    rank?: bigint;
}
export interface PartialScan {
    startedAt: Timestamp;
    businessName: string;
    results: Array<RankResult>;
    address: string;
    keyword: string;
    centerLat: number;
    centerLng: number;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControl(): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    clearLastPartialScan(): Promise<void>;
    deleteSavedSearch(searchId: SearchId): Promise<void>;
    getCallerUserRole(): Promise<UserRole>;
    getGridPoints(centerLat: number, centerLng: number): Promise<Array<[number, number]>>;
    getLastPartialScan(): Promise<PartialScan | null>;
    getSavedSearch(searchId: SearchId): Promise<SavedSearch | null>;
    getSerpApiKey(): Promise<string | null>;
    isCallerAdmin(): Promise<boolean>;
    listSavedSearches(): Promise<Array<SavedSearch>>;
    queryGridPoint(businessName: string, keyword: string, lat: number, lng: number, gridIndex: bigint): Promise<bigint | null>;
    saveSearch(input: SaveSearchInput): Promise<SearchId>;
    setSerpApiKey(apiKey: string): Promise<void>;
    startScan(businessName: string, keyword: string, address: string, centerLat: number, centerLng: number): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
}
import type { PartialScan as _PartialScan, RankResult as _RankResult, SaveSearchInput as _SaveSearchInput, SavedSearch as _SavedSearch, SearchId as _SearchId, Timestamp as _Timestamp, UserId as _UserId, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async clearLastPartialScan(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearLastPartialScan();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearLastPartialScan();
            return result;
        }
    }
    async deleteSavedSearch(arg0: SearchId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSavedSearch(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSavedSearch(arg0);
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGridPoints(arg0: number, arg1: number): Promise<Array<[number, number]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGridPoints(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGridPoints(arg0, arg1);
            return result;
        }
    }
    async getLastPartialScan(): Promise<PartialScan | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLastPartialScan();
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLastPartialScan();
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSavedSearch(arg0: SearchId): Promise<SavedSearch | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSavedSearch(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSavedSearch(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSerpApiKey(): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSerpApiKey();
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSerpApiKey();
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listSavedSearches(): Promise<Array<SavedSearch>> {
        if (this.processError) {
            try {
                const result = await this.actor.listSavedSearches();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listSavedSearches();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async queryGridPoint(arg0: string, arg1: string, arg2: number, arg3: number, arg4: bigint): Promise<bigint | null> {
        if (this.processError) {
            try {
                const result = await this.actor.queryGridPoint(arg0, arg1, arg2, arg3, arg4);
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.queryGridPoint(arg0, arg1, arg2, arg3, arg4);
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveSearch(arg0: SaveSearchInput): Promise<SearchId> {
        if (this.processError) {
            try {
                const result = await this.actor.saveSearch(to_candid_SaveSearchInput_n17(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveSearch(to_candid_SaveSearchInput_n17(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setSerpApiKey(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setSerpApiKey(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setSerpApiKey(arg0);
            return result;
        }
    }
    async startScan(arg0: string, arg1: string, arg2: string, arg3: number, arg4: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.startScan(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startScan(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
}
function from_candid_PartialScan_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PartialScan): PartialScan {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_RankResult_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RankResult): RankResult {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_SavedSearch_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SavedSearch): SavedSearch {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SavedSearch]): SavedSearch | null {
    return value.length === 0 ? null : from_candid_SavedSearch_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PartialScan]): PartialScan | null {
    return value.length === 0 ? null : from_candid_PartialScan_n6(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    lat: number;
    lng: number;
    rank: [] | [bigint];
}): {
    lat: number;
    lng: number;
    rank?: bigint;
} {
    return {
        lat: value.lat,
        lng: value.lng,
        rank: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.rank))
    };
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _SearchId;
    userId: _UserId;
    createdAt: _Timestamp;
    businessName: string;
    results: Array<_RankResult>;
    address: string;
    keyword: string;
    centerLat: number;
    centerLng: number;
}): {
    id: SearchId;
    userId: UserId;
    createdAt: Timestamp;
    businessName: string;
    results: Array<RankResult>;
    address: string;
    keyword: string;
    centerLat: number;
    centerLng: number;
} {
    return {
        id: value.id,
        userId: value.userId,
        createdAt: value.createdAt,
        businessName: value.businessName,
        results: from_candid_vec_n8(_uploadFile, _downloadFile, value.results),
        address: value.address,
        keyword: value.keyword,
        centerLat: value.centerLat,
        centerLng: value.centerLng
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    startedAt: _Timestamp;
    businessName: string;
    results: Array<_RankResult>;
    address: string;
    keyword: string;
    centerLat: number;
    centerLng: number;
}): {
    startedAt: Timestamp;
    businessName: string;
    results: Array<RankResult>;
    address: string;
    keyword: string;
    centerLat: number;
    centerLng: number;
} {
    return {
        startedAt: value.startedAt,
        businessName: value.businessName,
        results: from_candid_vec_n8(_uploadFile, _downloadFile, value.results),
        address: value.address,
        keyword: value.keyword,
        centerLat: value.centerLat,
        centerLng: value.centerLng
    };
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SavedSearch>): Array<SavedSearch> {
    return value.map((x)=>from_candid_SavedSearch_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RankResult>): Array<RankResult> {
    return value.map((x)=>from_candid_RankResult_n9(_uploadFile, _downloadFile, x));
}
function to_candid_RankResult_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RankResult): _RankResult {
    return to_candid_record_n21(_uploadFile, _downloadFile, value);
}
function to_candid_SaveSearchInput_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SaveSearchInput): _SaveSearchInput {
    return to_candid_record_n18(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    businessName: string;
    results: Array<RankResult>;
    address: string;
    keyword: string;
    centerLat: number;
    centerLng: number;
}): {
    businessName: string;
    results: Array<_RankResult>;
    address: string;
    keyword: string;
    centerLat: number;
    centerLng: number;
} {
    return {
        businessName: value.businessName,
        results: to_candid_vec_n19(_uploadFile, _downloadFile, value.results),
        address: value.address,
        keyword: value.keyword,
        centerLat: value.centerLat,
        centerLng: value.centerLng
    };
}
function to_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    lat: number;
    lng: number;
    rank?: bigint;
}): {
    lat: number;
    lng: number;
    rank: [] | [bigint];
} {
    return {
        lat: value.lat,
        lng: value.lng,
        rank: value.rank ? candid_some(value.rank) : candid_none()
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<RankResult>): Array<_RankResult> {
    return value.map((x)=>to_candid_RankResult_n20(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
